export enum TransactionStateEnum {
  PENDING_IN_MEMPOOL = 0,
  COMMITTED_IN_MEMPOOL = 1,
  REVERTING = 2,
  EXECUTING = 3,
  FAILED_REVERT = 4,
  FAILED_EXECUTION = 5,
  SUCCESSFUL_REVERT = 6,
  SUCCESSFUL_EXECUTION = 7,
}